#!/anaconda3/bin/python3
"""
This script performs aperture photometry on a set of images using the class
`astrolib.photo.stamp` for any number of aperture and annulus radii provided.

usage:
    apertures -c <apertures.cfg>

inputs:
    configs file:   contains parameters used by apertures and input file paths
    images file:    contains list of images to operate on
    sources file:   contains the id, ra and dec of all sources

outputs:
    .photo file:    a .photo file for each input image with columns
                        id, alpha, delta, sky, sky_std, +
                        ( flux, flux_err, mag, mag_err ) for each ap. radius
"""

from    __imports__ import *

##  ============================================================================
##  Setup

print(                                         )
print( "A P E R T U R E   P H O T O M E T R Y" )
print( "                           - astrolib" )
print(                                         )

##  Read in command line arguments.

cl_parser       = io.CL_Parser( sys.argv )
configs_file    = cl_parser.get_flag( "-c", default="apertures.cfg" )

##  Read in configs.

print( "Reading in %s for configs..." % configs_file )

configs         = io.get_configs( configs_file )

input_file      = configs["input_file"]
images_file     = configs["images_file"]
data_path       = configs["data_path"]

unit            = configs["unit"]
R               = configs["R"]
R_i             = configs["R_i"]
R_o             = configs["R_o"]
sigma           = configs["sigma"]
epsilon         = configs["epsilon"]

print()
for key in configs:
    print( key, (20 - len(key)) * " ", configs[ key ] )
print()

##  Create list of images from the images file.
##  Add the data path to the file list.

image_files     = [ im for im in io.read( images_file )["image"] ]

for i, im_file in enumerate( image_files ):
    image_files[i]  = os.path.join( data_path, im_file )

##  Read in sources from the input file.

print( "Reading %s for sources..." % input_file )

sources         = io.read( input_file )

##  Create the output array.
##  Add flux_, flux_err_, mag_, mag_err_ columns for each aperture R.

out_dtype   = {
    "names":    ["id", "alpha", "delta", "sky", "sky_std"],
    "formats":  ["i8", "f8", "f8", "f8", "f8"]
}

flux_cols       = []
flux_err_cols   = []
mag_cols        = []
mag_err_cols    = []

for i, r in enumerate( R ):

    flux_cols.append(       "flux_"     + str(r) )
    flux_err_cols.append(   "flux_err_" + str(r) )
    mag_cols.append(        "mag_"      + str(r) )
    mag_err_cols.append(    "mag_err_"  + str(r) )

    out_dtype["names"].append(      flux_cols[i]        )
    out_dtype["names"].append(      flux_err_cols[i]    )
    out_dtype["names"].append(      mag_cols[i]         )
    out_dtype["names"].append(      mag_err_cols[i]     )

    out_dtype["formats"].append( "f8" )
    out_dtype["formats"].append( "f8" )
    out_dtype["formats"].append( "f8" )
    out_dtype["formats"].append( "f8" )

photometry          = np.zeros( sources.size, dtype=out_dtype )
photometry["id"]    = sources["id"]
photometry["alpha"] = sources["alpha"]
photometry["delta"] = sources["delta"]

##  ============================================================================
##  Photometry

for im_file in image_files:

    ##  Create a stamp object and set the apertures and annulus.

    S       = 1.1 * np.max( R_o )
    stamp   = photo.stamp( photo.image(im_file), S=S, unit=unit )

    ##  For each source in the catalog...

    print()
    print( "Performing aperture photometry on %s..." % im_file )
    for key in ["pix_scale", "gain", "mag_0", "mag_0_err" ]:
        print( key, (20 - len(key)) * " ", stamp.image.__dict__[ key ] )
    print()

    for i, source in enumerate( sources ):

        io.progress( i, sources.size )

        ##  Set the data and annulus and calculate the sky.

        stamp.set_target( alpha=source["alpha"], delta=source["delta"] )

        ##  For each aperture radius given...

        for j in range( len(R) ):

            ##  Set the aperture and annulus.
            ##  Calculate the background and flux.

            stamp.set_aperture( R[j] )
            stamp.set_annulus( R_i[j], R_o[j] )
            stamp.calc_sky( sigma=sigma, epsilon=epsilon )
            stamp.calc_flux( subtract=True )

            ##  Write to the data array.

            R_str   = str( R[j] )

            photometry[i]["sky"]                = stamp.sky
            photometry[i]["sky_std"]            = stamp.sky_std
            photometry[i]["flux_" + R_str]      = stamp.flux
            photometry[i]["flux_err_" + R_str]  = stamp.flux_err
            photometry[i]["mag_" + R_str]       = stamp.mag
            photometry[i]["mag_err_" + R_str]   = stamp.mag_err

    ##  Create the output file path and write to file.

    out_file    = io.parse_path( im_file )[1] + ".photo"
    io.write( out_file, photometry )

print( "...done!" )
print()
