
package:
    name:     astrolib
    version:  "7.0"

source:
    git_url:  https://github.com/bleist88/astrolib.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - astropy
        - matplotlib
        - pyarrow

about:
    home:         https://github.com/bleist88/
    license:      GNU GPLv3
    license_file: LICENSE
