
package:
  name:     astrolib
  version:  6.2831853

source:
  git_url:  https://github.com/bleist88/astrolib.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - astropy
    - matplotlib

about:
  home:         https://github.com/bleist88/
  license:      GNU GPLv3
  license_file: LICENSE
